//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectZabolevaniya
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTH
    {
        public int IdAuth { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    }
}
