//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectZabolevaniya
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZabolevaniyaEntities2 : DbContext
    {
        public ZabolevaniyaEntities2()
            : base("name=ZabolevaniyaEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AUTH> AUTH { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Monitoring> Monitoring { get; set; }
        public virtual DbSet<Position> Position { get; set; }
        public virtual DbSet<REGA> REGA { get; set; }
        public virtual DbSet<Status> Status { get; set; }
    }
}
