//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectZabolevaniya
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monitoring
    {
        public int IdMon { get; set; }
        public System.DateTime DateBegin { get; set; }
        public System.DateTime DateExit { get; set; }
        public int IdEmp { get; set; }
        public int IdStatus { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Status Status { get; set; }
    }
}
